### ISSUE TITLE
Comparison to existing project `pokemon-colorscripts`

### ISSUE THREAD

**Issue by acxz** [talwat/pokeget#1]
Hey @talwat great project! I love when people make code around Pokemon!

I was wondering what the difference between this project and [pokemon-colorscripts](https://gitlab.com/phoneybadger/pokemon-colorscripts) is?

Sorry if I'm raining on your parade. But thought I'd let you know about this repo since I also wanted to make something like this and stopped myself before I did since I found there is already an active repo working on this idea and decided to use/contribute that repo instead.

Anyways this really is a great project and kudos to making it!

**Comment by talwat** [comment]
Hey! Thanks for asking.

While googling when I first came up with the idea, I found pokemon-colorscripts and actually used it as a source for pokeget to use at one point. However, the reason I continued making a seperate project is that pokemon-colorscripts has certain issues with the sprites being blurry, doesn't support gen 6 to gen 8, and is also a little more complex, and most of all gets it's sprites locally. pokemon-colorscripts is also not maintained anymore.

They are very simular though.

It would be super cool if you contributed here.

**Comment by acxz** [comment]
I see, I see. it's been a while so I hadn't realize they don't have the newer gens, and yeah some sprites just don't render well.

I'll def keep an eye on this repo!

**Comment by acxz** [comment]
If I may request, I would love to at least ensure feature parity with the predecessor pokemon-colorscripts repo.
Primarily this includes being able to select random pokemon and from certain gens.

From `pokemon-colorscripts -h`
```
  -r, --random, random	Show a random pokemon. This flag can optionally be
                        followed by a generation number or range (1-8) to show random
                        pokemon from a specific generation or range of generations.
                        The generations can be provided as a continuous range (eg. 1-3)
                        or as a list of generations (1 3 6)
```

Also a feature that is not present in `pokemon-colorscripts` but would be nice to have is being able to specify a pokemon by their national pokedex.

**Comment by talwat** [comment]
Sure! I have an internal todo list so I will definitely keep that in mind. Thanks a ton for the suggestions! :)

**Comment by talwat** [comment]
I also do agree that pokeget should have the same features as pokemon-colorscripts. I will probably implement random pokemon very soon.

**Comment by acxz** [comment]
I was kinda hoping this issue can be open until at least feature parity is accomplished.

**Comment by talwat** [comment]
Yeah that's probably a better idea. I will post updates here about which features have been added and such. Sorry for closing it :)

**Comment by talwat** [comment]
The option to get pokemon with both national dex id's **and** names has been added, although it is still experimental.

**Comment by talwat** [comment]
Another update: Random pokemon have now been added, although specific generations still need to be added. :)

**Comment by talwat** [comment]
Update: Random pokemon can now be from a specific generation. @acxz would you say it's alright to close the issue now?

**Comment by acxz** [comment]
Just tested it, thanks so much!!!

**Comment by acxz** [comment]
Took a look at this again and I don't think feature parity is reached. I can't select a random pokemon from multiple regions. I think this should be reopened.

**Comment by talwat** [comment]
I can add support for random pokemon across multiple generations soon, I will let you know when it's done so this issue can be resolved :)

**Comment by talwat** [comment]
Heya @acxz, this has now been added.
