### ISSUE TITLE
locally stored sprites

### ISSUE THREAD

**Issue by mekb-turtle** [talwat/pokeget#10]
would it be possible to have the sprites stored locally, when you run a command it'll fetch the sprites from here and store them locally. and if you use pokeget without the sprites downloaded it'll automatically download them, somewhere like `~/.cache/pokeget/sprites/`? like how neofetch automatically generates its config when ran if it doesn't exist

**Comment by talwat** [comment]
I might be able to add a caching system where every time you get a pokemon it saves the output, and then the next time it checks to see if what it wants is already in the cache.

**Comment by talwat** [comment]
I can also make it optional in the config file.

**Comment by mekb-turtle** [comment]
> I might be able to add a caching system where every time you get a pokemon it saves the output, and then the next time it checks to see if what it wants is already in the cache. Does that sound good?

ah yep, that sounds better, so it doesn't have to download all the pokemon at once, then have a flag that'll ignore the cache and fetch the new sprite (if there is a new sprite) and update the cache again

**Comment by talwat** [comment]
I think I could just have an option to turn the caching system on or off in the config file, and then a command to clear the cache.

**Comment by talwat** [comment]
Heya, an early implementation of this has just been added 🥳
