### ISSUE TITLE
Add comparison/description for pokeshell

### ISSUE THREAD

**Issue by acxz** [talwat/pokeget#13]
Would you be open to adding a comparison paragraph for pokeshell like you have for pokemon-colorscripts?

**Comment by talwat** [comment]
Sure, I might actually make a separate markdown file, to be honest.

**Comment by talwat** [comment]
A new section has been added in the README. Feel free to reopen this issue if you think anything is incorrect, or if you updated pokeshell you can make a new issue.

I wish you the best of luck developing pokeshell! :)
