### ISSUE TITLE
Random can sometimes fail

### ISSUE THREAD

**Issue by res0nance** [talwat/pokeget#18]
## Severity

Not severe

## Bug description

Shuf seems to fail for some reason, unsure if this is an implementation issue or a possibility of shuf

```
$ ./pokeget -random 7
[!] Using shuf for random number generation
[!] randomGenNum: -1
[!] finalRandomGen: 7
[!] randomGens: 7
[!] URL: https://raw.githubusercontent.com/talwat/pokeget-sprites/main/pokemon/big/809.txt
[!] Pokemon could not be found (404 Error/cat Error)
```

## What is supposed to happen

Gracefully handle shuf failures

## How to replicate

How do you replicate this bug? What commands do you run?

Ran `pokeget -random 7` till this was triggered

## Output of the doctor script

Doesn't run on windows

## Output of pokeget version

From the macos-random branch so near the tip of main

## How you installed pokeget

Cloned the script from, ran directly from the repository folder

## Any other information

Windows MinGW environment

**Comment by talwat** [comment]
Windows is **not** supported properly, so I'm unsure if this is a shuf error, a windows error, or a pokeget error. Can you try using the -debug flag while doing that and then when the bug appears copy-paste the output?
