### ISSUE TITLE
Add PokeAPI backend

### ISSUE THREAD

**Issue by acxz** [talwat/pokeget#6]
So I was wondering what sources other pokemon terminal tools use i.e. [pokeshell](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pokeshell) and I found they use the following API: [PokeAPI](https://pokeapi.co/?ref=hackernoon.com) github: https://github.com/PokeAPI

Here is the github repo with the sprites PokeAPI has: https://github.com/PokeAPI/sprites/tree/f301664fbbce6ccbe09f9561287e05653379f870

You can access it like so: https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/722.png

For example: 

![shiny-rowlet](https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/722.png)
This is different from reborn's version, where we currently have
![reborn-shiny-rowlet](https://user-images.githubusercontent.com/17132214/155373891-39910aeb-4530-4041-85ea-b0e633a07456.png)

Overall using PokeAPI would essentially allow us to take in much more sprite data (and it being official, instead of Reborn's rendition of the art).

P.S. Looking at the pokeshell script it does seem like they are using imagemagick to resize and also img2xterm to get the terminal art. Maybe these could be useful tools? idk just some observations.

**Comment by talwat** [comment]
Unfortunately, normal pokemon doesn't have pixel art versions of pokemon up to gen 7. However, I can implement a setting to instead of using pokeget's repository use a different one. In fact, right now, I already am implementing sprites from pokemondb.net. So I would be willing to add an option in the config file to use the API you recommended :)

**Comment by acxz** [comment]
> normal pokemon doesn't have pixel art versions of pokemon up to gen 7

I assume by normal you mean official.

That is true, however the [smogon community has created these](https://www.smogon.com/forums/threads/sword-shield-sprite-project.3647722/) (up to gen 8) and PokeAPI pulls from them. See [here](https://github.com/PokeAPI/sprites#generation-v) and [here](https://github.com/PokeAPI/sprites#thanks).

> I can implement a setting to instead of using pokeget's repository use a different one.

That would be nice, but I don't want you to do more work than you need haha.

> pokemondb.net

From what I can tell, pokemondb does not have pixel art versions of gen 8. Compare pokemondb's Grookey ![Grookey](https://img.pokemondb.net/sprites/home/normal/grookey.png) and PokeAPI's Grookey ![Grookey](https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/810.png).

**Comment by talwat** [comment]
This is actually really cool! I will do some digging and then I think it's actually okay to replace all of the current sprites with the ones from pokeAPI.

**Comment by talwat** [comment]
Also about the pokemondb thing, I wanted it since it has modern versions of the small sprites, but now I see it isn't necessary because of this new API.

**Comment by talwat** [comment]
Alright so the final thing I have decided to do is make an option in the config file to use the pokeAPI sprites. I had to shave them down removing megas, female versions, variants, and backsprites for my own sanity. This should leave the small sprites from there and the big sprites with official shiny colors that go up to gen 8 including gen 8. This will take some time to do. Super sorry for all the confusion.

**Comment by acxz** [comment]
Does this mean it won't be possible to use the mega forms from pokeAPI?

**Comment by talwat** [comment]
I may add it in the future, but unfortunately yes due to the whole naming scheme being very strange. I want to at least get something working with pokeAPI's sprites before adding megas.

**Comment by acxz** [comment]
Sounds good, its good to start small first.

If you get some time can you describe the issue you are having with the naming scheme?
I found the following file if it helps in terms of getting the pokemon's specific variant. https://github.com/PokeAPI/sprites/blob/b629bcff5088e01a5f8a4892328151331c3806d6/scripts/forms.json

**Comment by talwat** [comment]
It's due to the mega being counted separately. So all the megas have a completely separate count which is prefixed with '10'. At least, this is what I think. As for the .json file, it could be useful in the future for renaming things and such. I am also debating on making a separate repository for all the pokemon sprites, although this would break compatibility with old versions of pokeget so I need to make sure everything is perfect before doing so.

**Comment by talwat** [comment]
It will be done today :)

**Comment by talwat** [comment]
It has been implemented! If you set `getVanilla` to true it will pick those sprites instead.

**Comment by talwat** [comment]
Let me know when this issue can be closed.

**Comment by acxz** [comment]
> It has been implemented! If you set getVanilla to true it will pick those sprites instead.

Sweet just tested it and it works for me! Thanks so much!!!!

> Let me know when this issue can be closed.

I'd prefer this is kept open until we can add the variants just so we can an open issue to track it. If you want to devote your time elsewhere, I can try to tackle the issue this upcoming weekend.

**Comment by talwat** [comment]
Hey, because of the new shiny small sprites I have decided that **I** will not implement variants. It would just be too complicated and probably wouldn't be worth it. Sorry! If someone makes a PR I can merge it, but right now I want to get pokeget onto package managers like brew and make the install process as easy as possible with many options.

**Comment by acxz** [comment]
That's fine, should you add the wontfix label or the helpwanted label?

**Comment by talwat** [comment]
Maybe both? :^)
