### ISSUE TITLE
Small Shiny Sprites

### ISSUE THREAD

**Issue by acxz** [talwat/pokeget#9]
Hey talwat! Hope you are doing well!

pokemon-colorscripts [added](https://gitlab.com/phoneybadger/pokemon-colorscripts/-/merge_requests/5) shiny sprites so it'd be nice if we can also get shiny sprites in this repo.

**Comment by talwat** [comment]
Heya! Yeah, the source they found is actually really cool. I can add them to the vanilla sprites (PokeAPI) since they would fit best there.

**Comment by talwat** [comment]
It might take me a while to get around implementing, but I can do it. I also need to move the sprites to a separate repo (finally) and also improve the self update functionality a lot.

**Comment by talwat** [comment]
This has been added to vanilla sprites.
